import http from 'node:http';import crypto from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {store,permissions,normalizeInfoportal,createSnapshot,dashboard,audit,formTemplates} from './data.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url)); const web=path.resolve(__dirname,'../../web/public'); const port=process.env.PORT||3000;
function json(res,code,obj){res.writeHead(code,{'content-type':'application/json; charset=utf-8','x-content-type-options':'nosniff','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline'"});res.end(JSON.stringify(obj));}
async function body(req){let b='';for await(const c of req)b+=c;return b?JSON.parse(b):{};}
function requirePerm(req,res,perm){const role=req.headers['x-role']||'Administrator'; if(!(permissions[role]||[]).includes(perm)){json(res,403,{error:'Keine Berechtigung',required:perm});return false} return true}
const routes={
 'GET /api/health':(req,res)=>json(res,200,{status:'ok',app:'SicherheitsToolSchule'}),
 'GET /api/bootstrap':(req,res)=>json(res,200,{school:store.school,users:store.users,roles:Object.keys(permissions),permissions,classes:store.classes,students:store.students.map(({supportNeed,...s})=>s),exercises:store.exercises,assemblyPoints:store.assemblyPoints,formTemplates}),
 'POST /api/infoportal/config':async(req,res)=>{if(!requirePerm(req,res,'imports:run'))return; const b=await body(req); store.school.code=b.code||store.school.code; store.school.infoportalUrl=normalizeInfoportal(b.login||b.code); audit('admin','infoportal.configured','school',{url:store.school.infoportalUrl}); json(res,200,{providerOrder:['SchuleInfoportalApiProvider','SchuleInfoportalExportProvider','CsvImportProvider','ExcelImportProvider','ManualDataProvider','DemoProvider'],url:store.school.infoportalUrl});},
 'POST /api/import/demo':(req,res)=>{if(!requirePerm(req,res,'imports:run'))return; audit('admin','demo.imported','school',{students:store.students.length}); json(res,200,{imported:{teachers:1,students:store.students.length,classes:store.classes.length,absences:store.absences.length}})},
 'POST /api/exercises':async(req,res)=>{if(!requirePerm(req,res,'exercises:manage'))return; const b=await body(req); const ex={id:'ex'+(store.exercises.length+1),status:'geplant',...b}; store.exercises.push(ex); store.tasks.push({id:'t'+store.tasks.length,title:'Übungsmappe erzeugen',exerciseId:ex.id,status:'neu'}); store.calendar.push({id:'cal'+store.calendar.length,title:ex.title,date:ex.date,type:'Probealarm'}); audit('safety','exercise.created','exercise',{id:ex.id}); json(res,201,ex)},
 'POST /api/exercises/approve':async(req,res)=>{if(!requirePerm(req,res,'exercises:approve'))return; const b=await body(req); const ex=store.exercises.find(e=>e.id===b.exerciseId); if(!ex)return json(res,404,{error:'Nicht gefunden'}); ex.status='freigegeben'; ex.approvedBy=b.userId||'u-head'; audit('head','exercise.approved','exercise',{id:ex.id}); json(res,200,ex)},
 'POST /api/exercises/snapshot':async(req,res)=>{if(!requirePerm(req,res,'exercises:manage'))return; try{json(res,201,{items:createSnapshot((await body(req)).exerciseId)})}catch(e){json(res,404,{error:e.message})}},
 'POST /api/attendance':async(req,res)=>{if(!requirePerm(req,res,'attendance:report'))return; const b=await body(req); const r={id:b.clientId||crypto.randomUUID?.()||String(Date.now()),submittedAt:new Date().toISOString(),...b}; if(!store.attendanceReports.some(x=>x.id===r.id)) store.attendanceReports.push(r); audit('teacher','attendance.reported','attendance',{group:r.group}); json(res,201,r)},
 'GET /api/dashboard':(req,res)=>json(res,200,dashboard(new URL(req.url,'http://x').searchParams.get('exerciseId')||'ex1')),
 'GET /api/exports/attendance.csv':(req,res)=>{const rows=dashboard(new URL(req.url,'http://x').searchParams.get('exerciseId')||'ex1').missing.map(m=>`${m.personName};${m.group};${m.assemblyPointId}`);res.writeHead(200,{'content-type':'text/csv; charset=utf-8'});res.end('Name;Gruppe;Sammelplatz\n'+rows.join('\n'))},
 'GET /api/audit':(req,res)=>{if(!requirePerm(req,res,'audit:view'))return; json(res,200,{items:store.audit})}
};
http.createServer(async(req,res)=>{const key=req.method+' '+req.url.split('?')[0]; if(routes[key]) return routes[key](req,res); let p=path.join(web, req.url==='/'?'index.html':req.url); if(!p.startsWith(web)) return json(res,400,{error:'Bad path'}); fs.readFile(p,(e,d)=>{if(e){res.writeHead(404);res.end('Nicht gefunden')}else{res.writeHead(200,{'content-type':p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.json')?'application/json':'text/html'});res.end(d)}})}).listen(port,()=>console.log(`SicherheitsToolSchule läuft auf http://localhost:${port}`));
